[package]
name = "count-triplets-that-can-form-two-arrays-of-equal-xor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
